version: 0.0
os: linux

phases:
  build:
    commands:
      - echo Entered the build phase
      - mvn clean package
  post_build:
    commands:
       - echo Build completed successfully
artifacts:
  files:
    -'**/*'
